on:
  # Triggers the workflow nightly (at midnight)
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  identify:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      # inspiration: https://brunoscheufler.com/blog/2021-10-09-generating-dynamic-github-actions-workflows-with-the-job-matrix-strategy
      - id: matrix
        run: |
          ./print_versions.sh
          echo "::set-output name=matrix::$(cat all |  jq -Rsc '. / "\n" - [""]')"
          echo "::set-output name=latest::$(cat latest |  jq -Rsc '. / "\n" - [""]')"

  debug:
    needs: [ identify ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"

  debug-latest:
    needs: [ identify ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.latest)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"

  # pubhish:
  #   needs: [ identify ]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       value: ${{fromJson(needs.setup.outputs.matrix)}}
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.5
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1.2.0
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1.6.0
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         push: true
  #         build-args: ${{ matrix.value }}
  #         tags: butkovic/activemq:${{ matrix.value }}

  # pubhish-latest:
  #   needs: [ identify ]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       value: ${{fromJson(needs.setup.outputs.latest)}}
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.5
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1.2.0
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1.6.0
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         push: true
  #         build-args: ${{ matrix.value }}
  #         tags: butkovic/activemq:latest
