on:
  # Triggers the workflow nightly (at midnight)
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  URL_RELEASES: https://archive.apache.org/dist/activemq
  URL_TAGS: https://registry.hub.docker.com/v2/repositories/butkovic/activemq/tags?page_size=1024

jobs:

  identify:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - id: matrix
        run: |
          echo "python print_versions.py -r $URL_RELEASES -t $URL_TAGS"
          echo "python print_versions.py -r $URL_RELEASES -t $URL_TAGS --latest-only"
          echo "::set-output name=matrix::$(python print_versions.py -r $URL_RELEASES -t $URL_TAGS)"
          echo "::set-output name=latest::$(python print_versions.py -r $URL_RELEASES -t $URL_TAGS --latest-only)"

  debug:
    needs: [ identify ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"

  debug-latest:
    needs: [ identify ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.latest)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"

  # pubhish:
  #   needs: [ identify ]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       value: ${{fromJson(needs.setup.outputs.matrix)}}
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.5
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1.2.0
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1.6.0
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         push: true
  #         build-args: ${{ matrix.value }}
  #         tags: butkovic/activemq:${{ matrix.value }}

  # pubhish-latest:
  #   needs: [ identify ]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       value: ${{fromJson(needs.setup.outputs.latest)}}
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.5
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1.2.0
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1.6.0
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         push: true
  #         build-args: ${{ matrix.value }}
  #         tags: butkovic/activemq:latest
