on:
  push:
    branches:
      - main

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1,2,3]
    steps:
      - run: |
          echo Matrix value: "${{ matrix.version }}"
          echo Matrix one but last value: "${{ matrix.version[-1] }}"
#      - if: ${{ matrix.version[-1] }} == ${{ matrix.value }}
#        run: |
#          echo Matrix value (latest): "${{ matrix.value }}"