on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        run: |
          echo "::set-output name=matrix::[\"1\",\"2\"]"

  job2:
    needs: [ job1 ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: |
          echo Current: "${{ matrix.value }}"
          echo All "${{fromJson(needs.job1.outputs.matrix)}}"
          echo Last: "${{fromJson(needs.job1.outputs.matrix)[-1]}}"